[build]
builder = "DOCKERFILE"
buildCommand = ""
watchPatterns = ["app/**", "public/**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 