[build]
builder = "nixpacks"
installCommand = "npm install --legacy-peer-deps"
buildCommand = "npm run build"
startCommand = "npm start"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 