[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = ""
watchPatterns = ["app/**", "public/**"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 